// Filter Strings
// Titles
SFLTitleCreateFilter	       "Create Filter"
SFLTitleEditFilter_S	       "Edit Filter %S"
SFLTitleGain                 "Gain"
SFLTitleEditFields           "Edit Fields"

// Remarks
SFLRemNotValidFilterName   "Not a valid filter name"
SFLRemFilExists	       "Filter already exists"
SFLRemWrongFilterSize      "Filter rows and columns must be odd and positive"
SFLRemGain                 "Gain"

// Errors
SFLErrNoLinFilter_S        "%S is no Linear Filter"
SFLErrError                "Error"

// Items
SFLUiFilName "&Filter Name"
SFLUiType "&Type"
SFLUiLinearFilter       "&Linear Filter"
SFLUiRows	       "&Rows"
SFLUiColumns	       "&Columns"
SFLUiRealMatrix	       "&Real Matrix"
SFLUiDescription        "&Description:"
SFLUiGain	       "&Gain"
SFLUiValue  "&Value"
