// GeoRef3D, Display3D Strings
// Titles
S3DTitleGeoRef3DEditor_s "GeoRef 3D Editor: %S"
S3DTitleGeoRef3DEditor "GeoRef 3D Editor"
S3DTitleDisplay3D  "Display 3D"
S3DTitleExtendBoundaries "Extend Boundaries"
S3DTitleConfigure "Customize"
S3DTitleViewPoint "Set View Point"

// Remarks
S3DRemPressRedraw  "Press Redraw button to apply changed parameters"

// Items
S3DUiViewingAngle "Viewing &Angle"
S3DUiScaleHeight  "&Scale Height"
S3DUiDistance	 "&Distance"
S3DUiViewCoordsX	 "&Focal point"
S3DUiViewCoordsY	 "&Focal point Y"
S3DUiLocCoordsX	 "&View point"
S3DUiLocCoordsY	 "&View point Y"
S3DUiLocHeight	 "View point &height"
S3DUiHorRot	 "&Horizontal Rotation"
S3DUiVerRot	 "&Vertical Rotation"
S3DUiGrf         "&GeoReference"
S3DUiViewAngleColor "View angle"
S3DUiViewAxisColor "View axis"
S3DUiDisplayOptions "Display options"

//Error
S3ErrDTMNotValid   "DTM is not valid"
