// error codes
SDErrorNr                ErrorCode %i
SDErrUnknown             Unknown error
SDErrInsuffMem           Insufficient memory
SDErrCreate              Create error
SDErrFind                Find error
SDErrRead                Read error
SDErrWrite               Write error
SDErrAccess              Access violation error
SDErrDiskFull            Disk full
SDErrWrongType           Wrong type
SDErrBinaryVersionNotSupported_S "This binary version( %S) of the data file(s) is not supported"
SDErrModuleVersionNotSupported_S "This module interface version( %S) of the plugin %S is not supported"
SDErrODFVersionNotSupported_S "This Object definition version( %S) of the data file(s) is not supported"

// 'data type' names
SDFile                   File
SDBuffer                 Buffer
SDMap                    Map
SDTable                  Table
SDColumn                 Column
SDSegment                Segment
SDSegmentMap             Segment map
SDPolygon                Polygon
SDPolygonMap             Polygon map
SDLut                    Look up table
SDHist                   Histogram
SDDomain                 Domain
SDProjections            Projection
SDGeoRef                 Georeference
SDPointMap               Point map

// general user interface strings
SDUiInpMap               &Input Map
SDUiOutMap               &Output Map
SDUiRange		 Value &Range
SDUiInpRange             &Input Range
SDUiOutRange             &Output Range
SDUiPercentage           &Percentage

// form buttons
SDUiCancel           Cancel
SDUiOK               OK
SDUiHelp             &Help
SDUiStop             &Stop


// tranquilize
SDCalcHist           Calculating histogram

// principal components
SDPcInitPC                     Initializing Principal Components
SDPcRdErrNewWarn               Read Error. Create new matrices
SDPcCalcVarcovMat              Calculating variance-covariance matrix
SDPcCalcCorrMat                Calculating correlation matrix
SDPcCalcVarcovEigMat           Calculating var.-covar. Eigen matrix
SDPcCalcCorrEigMat             Calculating correlation Eigen matrix
SDPcmp                         Principal Components

// matrix
SDMatSingular   Singular
SDMatNonSymmetric  Nonsymmetric
SDMatNoEigenValues Can't calculate Eigen values
