// Other Object Strings
// Titles
SOOTitleCreateFunction "Create Function"
SOOTitleCreateScript "Create Script"

// Remarks
SOORemNotValidFunName "Not a valid function name"
SOORemFunExists "Function already exists"
SOORemInternalFunction "Function is an internal calculator function"
SOORemParserFunction "Function is an internal parser function"
SOORemNeighbourhoodFunction "Function is an internal neighbourhood function"
SOORemReservedWord "Function is a reserved word"
SOORemInvalidScriptName     "Not a valid script name"
SOORemScriptExists          "Script already exists"

// Items
SOOUiFunctionName "Function &Name"
SOOUiExpression  "&Expression:"
SOOUiDescription "&Description:"
SOOUiScriptName  "Script &Name"
SOOUiFunctionText "Function &Text:"
SOOUiScriptText "Script &Text:"

//Errors
SOOUiErrorNameConflict1     "Name Conflict. Two different files with the same name but located in different directories\n are copied to the same directory. Copy aborted."
SOOUiErrorNameConflict2_S     "\n The files are : %S and\n %S"
