// Pixel Info Strings
// Titles
SPITitlePixelInfo "Pixel Information"
SPITitleCnfPixInfo "Customize Pixel Info"
SPITitleAddMap   "Pixel Info - Add Map"
SPITitleAddCsys  "Pixel Info - Add Coordinate System"
SPITitleAddGrf   "Pixel Info - Add GeoReference"

// Errors
SPIErrMapNotFound_s  "Map %S not found"
SPIErrCsyNotFound_s  "Coordinate System %S not found"
SPIErrImpossibleCoord  "? impossible coordinate"
SPIErrOutsideMap       "? outside map"
SPIErrNoCoordinate     "? No Coordinate"

// Remarks
SPIRemRecvCoordFrom  "Receive coordinate data from:"
SPIRemShowValuesOf	 "Show values of:"
SPIRemCoordinate  "Coordinate"
SPIRemCnfPixInfo "Customize the Pixel Information Window"
SPIRemPrintPixelInfo    "Print Pixel Info"

// Items
SPIUiMouse  "&Mouse"
SPIUiContinuous "&Continuous"
SPIUiDigitizer "&Digitizer"
SPIUiPrintAt_ss     "Print at %s on %s"
SPIUiSelectFont     "&Font..."
