// Join Wizard Strings
// Titles
#define SJWTitleInputCol               ILWSF("JoinWizard", 1)
#define SJWTitleOutputCol              ILWSF("JoinWizard", 2)
#define SJWTitleJoinMethod             ILWSF("JoinWizard", 3)
#define SJWTitleLink                   ILWSF("JoinWizard", 4)
#define SJWTitleAggr                   ILWSF("JoinWizard", 5)
#define SJWTitleAggrMethod             ILWSF("JoinWizard", 6)
// Intros
#define SJWIntroInputCol               ILWSF("JoinWizard", 100)
#define SJWIntroOutputCol              ILWSF("JoinWizard", 101)
#define SJWIntroJoinMethod1            ILWSF("JoinWizard", 102)
#define SJWIntroJoinMethod2            ILWSF("JoinWizard", 103)
#define SJWIntroAggr                   ILWSF("JoinWizard", 104)
#define SJWIntroLink1A                 ILWSF("JoinWizard", 105)
#define SJWIntroLink1B                 ILWSF("JoinWizard", 106)
#define SJWIntroLink2A                 ILWSF("JoinWizard", 107)
#define SJWIntroLink2B                 ILWSF("JoinWizard", 108)
#define SJWIntroLink3A                 ILWSF("JoinWizard", 109)
#define SJWIntroLink3B                 ILWSF("JoinWizard", 110)
// Remarks
#define SJWRemNone1                    ILWSF("JoinWizard", 200)
#define SJWRemNone2                    ILWSF("JoinWizard", 201)
#define SJWRemAggr1                    ILWSF("JoinWizard", 202)
#define SJWRemAggr2_SS                 ILWSF("JoinWizard", 203)
#define SJWRemAggr3_S                  ILWSF("JoinWizard", 204)
#define SJWRemUseWeight                ILWSF("JoinWizard", 205)
#define SJWRemColExists                ILWSF("JoinWizard", 206)
// other
#define SJWJoinType1                   ILWSF("JoinWizard", 300)
#define SJWJoinType2                   ILWSF("JoinWizard", 301)
#define SJWJoinType3                   ILWSF("JoinWizard", 302)
#define SJWJoinType4                   ILWSF("JoinWizard", 303)
#define SJWCurrentTable                ILWSF("JoinWizard", 400)
#define SJWSelectedTable               ILWSF("JoinWizard", 401)
#define SJWSelectedJoinCol             ILWSF("JoinWizard", 402)
#define SJWKey1                        ILWSF("JoinWizard", 403)
#define SJWKey2                        ILWSF("JoinWizard", 404)
#define SJWTableDomain_S               ILWSF("JoinWizard", 405)
#define SJWToBeSelected                ILWSF("JoinWizard", 406)
