// Tranquilizer messages (Captions)
#define SMPLTextCalculateVarcovMatrix  ILWSF("maplist", 1)
// Tranquilizer messages (Text)
#define SMPLTextCalculating            ILWSF("maplist", 100)
#define SMPLTextConstructing           ILWSF("maplist", 101)
#define SMPLTextCalculatingMap         ILWSF("maplist", 102)
// General Messages (Msg)
// Title messages (Title)
// Warnings (Warn)
// Error messages (Err)
#define SMPLErrEmptyMapList            ILWSF("maplist", 500)
#define SMPLErrDomainNoneNotAllowed    ILWSF("maplist", 501)
#define SMPLErrDomainGeoRefMismatch_S  ILWSF("maplist", 502)
// Other strings
