// Remarks
#define SSCRRemScript                  ILWSF("Script", 1)
#define SSCRRemParams                  ILWSF("Script", 2)
#define SSCRemDefault                  ILWSF("Script", 3)
#define SSCRRemName                    ILWSF("Script", 4)
#define SSCRRemType                    ILWSF("Script", 5)
// User Interface
#define SSCRUiParams                   ILWSF("Script", 100)
#define SSCRUiParam_d                  ILWSF("Script", 101)
#define SSCRUiSaveED_S                 ILWSF("Script", 102)
#define SSCRUiScrEditor                ILWSF("Script", 103)
#define SSCRUiDFunEditor               ILWSF("Script", 104)
#define SSCRUiIncludeExt               ILWSF("Script", 105)
// Parameter Types
#define SSCRPtString                   ILWSF("Script", 200)
#define SSCRPtValue                    ILWSF("Script", 201)
#define SSCRPtDomain                   ILWSF("Script", 202)
#define SSCRPtRpr                      ILWSF("Script", 203)
#define SSCRPtGeoRef                   ILWSF("Script", 204)
#define SSCRPtCoordSys                 ILWSF("Script", 205)
#define SSCRPtRasMap                   ILWSF("Script", 206)
#define SSCRPtSegMap                   ILWSF("Script", 207)
#define SSCRPtPolMap                   ILWSF("Script", 208)
#define SSCRPtPntMap                   ILWSF("Script", 209)
#define SSCRPtTable                    ILWSF("Script", 210)
#define SSCRPtMapView                  ILWSF("Script", 211)
#define SSCRPtMapList                  ILWSF("Script", 212)
#define SSCRPtTbl2d                    ILWSF("Script", 213)
#define SSCRPtAnnTxt                   ILWSF("Script", 214)
#define SSCRPtSms                      ILWSF("Script", 215)
#define SSCRPtMatrix                   ILWSF("Script", 216)
#define SSCRPtFilter                   ILWSF("Script", 217)
#define SSCRPtFunction                 ILWSF("Script", 218)
#define SSCRPtScript                   ILWSF("Script", 219)
#define SSCRPtColumn                   ILWSF("Script", 220)
#define SSCRPtFileName                 ILWSF("Script", 221)
