// User Interface Strings
// General
#define SUIOK                          ILWSF("Userint", 1)
#define SUICancel                      ILWSF("Userint", 2)
#define SUIHelp                        ILWSF("Userint", 3)
#define SUICopy                        ILWSF("Userint", 4)
#define SUIPrint                       ILWSF("Userint", 5)
#define SUIStop                        ILWSF("Userint", 6)
#define SUIYes                         ILWSF("Userint", 7)
#define SUINo                          ILWSF("Userint", 8)
#define SUINew                         ILWSF("Userint", 9)
#define SUIShow                        ILWSF("Userint", 10)
#define SUIDefine                      ILWSF("Userint", 11)
#define SUICalc                        ILWSF("Userint", 12)
#define SUIClose                       ILWSF("Userint", 13)
// Data Type Large object names
#define SUIObjMaps                     ILWSF("Userint", 100)
#define SUIObjMpv                      ILWSF("Userint", 101)
#define SUIObjMpr                      ILWSF("Userint", 102)
#define SUIObjMps                      ILWSF("Userint", 103)
#define SUIObjMpa                      ILWSF("Userint", 104)
#define SUIObjMpp                      ILWSF("Userint", 105)
#define SUIObjMpl                      ILWSF("Userint", 106)
#define SUIObjTbt                      ILWSF("Userint", 107)
#define SUIObjDom                      ILWSF("Userint", 108)
#define SUIObjRpr                      ILWSF("Userint", 109)
#define SUIObjCsy                      ILWSF("Userint", 110)
#define SUIObjGrf                      ILWSF("Userint", 111)
#define SUIObjHis                      ILWSF("Userint", 112)
#define SUIObjSms                      ILWSF("Userint", 113)
#define SUIObjMat                      ILWSF("Userint", 114)
#define SUIObjFun                      ILWSF("Userint", 115)
#define SUIObjFil                      ILWSF("Userint", 116)
#define SUIObjIsl                      ILWSF("Userint", 117)
#define SUIObjIlw                      ILWSF("Userint", 118)
#define SUIObjHsa                      ILWSF("Userint", 119)
#define SUIObjHss                      ILWSF("Userint", 120)
#define SUIObjHsp                      ILWSF("Userint", 121)
#define SUIObjTa2                      ILWSF("Userint", 122)
#define SUIObjAtx                      ILWSF("Userint", 123)
#define SUIObjIoc                      ILWSF("Userint", 124)
#define SUIObjIlo                      ILWSF("Userint", 125)
#define SUIObjGrh                      ILWSF("Userint", 126)
#define SUIObjStp                      ILWSF("Userint", 127)
#define SUIObjSmc                      ILWSF("Userint", 128)
// Composed Fields
#define SUIUiValRange                  ILWSF("Userint", 200)
#define SUIUiStepSize                  ILWSF("Userint", 201)
#define SUIFldName                     ILWSF("Userint", 202)
#define SUIFldCode                     ILWSF("Userint", 203)
#define SUIFldColor                    ILWSF("Userint", 204)
#define SUIFontName                    ILWSF("Userint", 205)
#define SUIFontSize                    ILWSF("Userint", 206)
#define SUIFontBold                    ILWSF("Userint", 207)
#define SUIFontItalic                  ILWSF("Userint", 208)
#define SUIFontRotation                ILWSF("Userint", 209)
// Remarks
#define SUiRemImageRange               ILWSF("Userint", 300)
#define SUIRemNotUsedByObjects         ILWSF("Userint", 301)
// Justification
#define SDUIJstTop                     ILWSF("Userint", 400)
#define SDUIJstBaseline                ILWSF("Userint", 401)
#define SDUIJstBottom                  ILWSF("Userint", 402)
#define SDUIJstLeft                    ILWSF("Userint", 403)
#define SDUIJstCenter                  ILWSF("Userint", 404)
#define SDUIJstRight                   ILWSF("Userint", 405)
// Messages
#define SUIMsgDirectory_               ILWSF("Userint", 500)
#define SUIDescription                 ILWSF("Userint", 501)
// Titles
#define SUITitleCreateMapList          ILWSF("Userint", 600)
#define SUITitleAddToDomain            ILWSF("Userint", 601)
#define SUITitleCreateRPR              ILWSF("Userint", 602)
#define SDUiTitleDescription           ILWSF("Userint", 603)
#define SUITitleToolBar                ILWSF("Userint", 604)
#define SUITitleProgress               ILWSF("Userint", 605)
// ILWIS Objects
#define SUIMapList                     ILWSF("Userint", 700)
// Errors
#define SUIErrInvalidMapListName       ILWSF("Userint", 800)
#define SUIErrMapListExists            ILWSF("Userint", 801)
#define SUIErrProgrammingError         ILWSF("Userint", 802)
#define SUIErrEnableNotImplem          ILWSF("Userint", 803)
#define SUIErrDisableNotImplem         ILWSF("Userint", 804)
#define SUIErrInvalidFolderChange      ILWSF("Userint", 805)
// Printer
#define SUIMsgPage                     ILWSF("Userint", 900)
// Extents/boundary
#define SUiExtCornersOfCorners         ILWSF("Userint", 1000)
#define SUiExtTopLeft                  ILWSF("Userint", 1001)
#define SUiExtTopRight                 ILWSF("Userint", 1002)
#define SUiExtBottomLeft               ILWSF("Userint", 1003)
#define SUiExtBottomRight              ILWSF("Userint", 1004)
